model:
  g: 9.81

  m_c: 0.390

  m_p: 0.614
  h_p: 0.154

  wheel_radius: 0.035
  wheel_base: 0.183

ctrl:
  theta_k: 3.0
  theta_dot_k: 2.3
  x_k: 0.0 #0.5
  x_dot_k: -2.0
  omega_k: -0.05
  x_dot_abs_max: 2.0

joy:
  k_j_omega: -5.0
  k_j_x_dot: -1.0

test:
  vector:
    dtype: "f4"
    shape: [3]
    data: [1.2, 1.6, 1.6]
    order: "C"
  matrix:
    dtype: "u8"
    shape: [3, 3]
    data: [
        1, 1, 2,
        1, 1, 2,
        1, 1, 2,
    ]
    order: "F"
